apiVersion: apps/v1
kind: Deployment
metadata:
  name: radardb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: radardb
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: radar
            - name: POSTGRES_PASSWORD
              value: "111"
            - name: POSTGRES_DB
              value: radardb
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP