apiVersion: v1
kind: Secret
metadata:
  name: radar-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  telegramBotToken: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
  telegramChatId: {{ .Values.secrets.telegramChatId | b64enc | quote }}
  polygonscanApiKey: {{ .Values.secrets.polygonscanApiKey | b64enc | quote }}