apiVersion: v1
kind: Service
metadata:
  name: radar
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: radar
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 8000
      targetPort: 8000
      name: metrics
  type: ClusterIP