image:
  repository: ghcr.io/omgoo191/radar
  tag: sha-c8edc963c9f889e66139295220ad25b11c0d07bc
  pullPolicy: Always

env:
  DATABASE_URL: "postgresql+asyncpg://radar:111@postgres:5432/radardb"

secrets:
  telegramBotToken: ""
  telegramChatId: ""
  polygonscanApiKey: ""

replicaCount: 1