image:
  repository: ghcr.io/omgoo191/radar
  tag: sha-e12aff1af4b8e730a0c982b843225022f9c6e691
  pullPolicy: Always

env:
  DATABASE_URL: "postgresql+asyncpg://radar:111@postgres:5432/radardb"

secrets:
  telegramBotToken: ""
  telegramChatId: ""
  polygonscanApiKey: ""

replicaCount: 1