image:
  repository: ghcr.io/omgoo191/radar
  tag: sha-b47cad43588de3aa687d0120af1633b4d4243fd1
  pullPolicy: Always

env:
  DATABASE_URL: "postgresql+asyncpg://radar:111@postgres:5432/radardb"

secrets:
  telegramBotToken: ""
  telegramChatId: ""
  polygonscanApiKey: ""

replicaCount: 1